routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// pruebas
Route::get('/poblar/auditoria', 'AuditoriaController@poblar_auditoria');
Route::get('/prueba', 'PruebaController@index');
//Route::get('/pruebita', 'PruebaController@mundo');
Route::get('/pruebita', function () {
    return view('welcome');
});

// Vista
Route::get('/usuarios', 'UsuarioController@index')->name('usuarios');


// Crear
Route::get('/usuarios/create', 'UsuarioController@create')->name('usuarios.create');
// Actualizar
// Borrar

// Socios
Route::resource('/socios', 'SocioController');

app/Auditoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Auditoria extends Model
{
		public $timestamps = false;
    protected $table = "T99999_Auditoria";
    protected $fillable = ['Nb_Tabla', 'Co_Tipo_Operacion', 'Tx_Sentencia','Co_Usuario'];

}

app/Bitacora.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bitacora extends Model
{
		protected $table = "T99999_Bitacora";
		public $timestamps = false;
    //protected $fillable = [];
		
		public function usuario()
    {
        return $this->hasOne(Usuario::class);
    }
}

app/Prueba.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Prueba extends Model
{
    //
}

app/Socio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Socio extends Model
{
    use SoftDeletes;

		public $timestamps = false;
    protected $table = "T00210_Socio";
    protected $fillable = ['Nb_Socio', 'Tx_Email', 'Co_Identificacion'];
    protected $primaryKey = 'Co_Socio';
    protected $dates = ['deleted_at'];
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
   protected $table = "T00100_Usuario";
}

app/Usuario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Usuario extends Model
{
    protected $table = "T00100_Usuario";
		protected $fillable = ['Nb_Usuario', 'Tx_Email', 'Tx_Clave' ];
		public $timestamps = false;

		public function bitacora()
    {
        return $this->belongsTo(Bitacora::class);
    }
}

app/Http/Controllers/AuditoriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AuditoriaController extends Controller
{
    //
		public function poblar_auditoria(){
			$audit = User::factory()->count(3)->make();
		}
}

app/Http/Controllers/BitacoraController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BitacoraController extends Controller
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PruebaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PruebaController extends Controller
{
	public function index(){
   return view('prueba.index',compact('pruebas'));
	}
	public function mundo(){
   return view('hola');
	}
}

app/Http/Controllers/SocioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Socio;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Redirect;

class SocioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $socios = Socio::all();
        return View::make('socios/index')->with('socios', $socios);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return View::make('socios/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $socio = new Socio();
        $socio->Nb_Socio = $request->Nb_Socio;
        $socio->Co_Identificacion = $request->Co_Identificacion;
        $socio->Tx_Email = $request->Tx_Email;
        $socio->save();

        return Redirect::route('socios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $socio = Socio::where('Co_Socio', $id)->first();
        return View::make('socios/show')->with('socio', $socio);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $socio = Socio::where('Co_Socio', $id)->first();
        return View::make('socios/edit')->with('socio', $socio)->with('id', $id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $socio = Socio::where('Co_Socio', $id)->first();
        $socio->Nb_Socio = $request->Nb_Socio;
        $socio->Co_Identificacion = $request->Co_Identificacion;
        $socio->Tx_Email = $request->Tx_Email;
        $socio->save();

        return Redirect::route('socios.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $socio = Socio::find($id)->delete();
        return Redirect::route('socios.index');
    }
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Usuario;

class UsuarioController extends Controller
{
	public function index(){
      $usuarios = Usuario::select('*')->get();
      return view('usuario.index')->with('usuarios',$usuarios);
   }

}

resources/views/hola.blade.php
Hola, mundo!

resources/views/layouts/app.blade.php
<!DOCTYPE html>

<html>

<head>

    <title>Laravel 7 CRUD Application - ItSolutionStuff.com</title>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">

</head>

<body>



<div class="container">

    @yield('content')

</div>



</body>

</html>

resources/views/prueba/index.blade.php
Hola, mundo!!

resources/views/socios/create.blade.php
@extends('layouts.app')
@section('content')

  <div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
          <h2>Agregar Socio</h2>
        </div>
        <div class="pull-right">
          <a class="btn btn-primary" href="{{ route('socios.index') }}"> Regresar</a>
      </div>
    </div>
  </div>

  @if ($errors->any())
    <div class="alert alert-danger">
      <strong>Whoops!</strong> There were some problems with your input.<br><br>
      <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
      </ul>
    </div>
  @endif

  <form action="{{ route('socios.store') }}" method="POST">
    @csrf
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Name:</strong>
          <input type="text" name="Nb_Socio" class="form-control">
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Identificación:</strong>
          <input type="text" name="Co_Identificacion" class="form-control">
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Email:</strong>
          <input type="text" name="Tx_Email" class="form-control">
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
        <button type="submit" class="btn btn-success">Agregar Socio</button>
      </div>
    </div>
  </form>
@endsection

resources/views/socios/edit.blade.php
@extends('layouts.app')
@section('content')

  <div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
          <h2>Editar Socio</h2>
        </div>
        <div class="pull-right">
          <a class="btn btn-primary" href="{{ route('socios.index') }}"> Regresar</a>
      </div>
    </div>
  </div>

  @if ($errors->any())
    <div class="alert alert-danger">
      <strong>Whoops!</strong> There were some problems with your input.<br><br>
      <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
      </ul>
    </div>
  @endif

  <form action="{{ route('socios.update', $id) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Name:</strong>
          <input type="text" name="Nb_Socio" class="form-control" value="{{ $socio->Nb_Socio }}">
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Identificación:</strong>
          <input type="text" name="Co_Identificacion" class="form-control" value="{{ $socio->Co_Identificacion }}">
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Email:</strong>
          <input type="text" name="Tx_Email" class="form-control" value="{{ $socio->Tx_Email }}">
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
        <button type="submit" class="btn btn-success">Editar Socio</button>
      </div>
    </div>
  </form>
@endsection

resources/views/socios/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
      <div class="col-lg-12 margin-tb">
        <div class="pull-left">
          <h2>Amazon - Socios</h2>
        </div>
        <div class="pull-right">
          <a class="btn btn-success" href="{{ route('socios.create') }}">Crear Socio</a>
        </div>
      </div>
    </div>

    <table class="table table-bordered">
      <thead>
        <tr class="text-center">
          <th class="text-center">ID</th>
          <th class="text-center">Nombre</th>
          <th class="text-center">Email</th>
          <th class="text-center">Movil</th>
          <th class="text-center">Calificación</th>
          <th class="text-center">Bloqueo</th>
          <th class="text-center">Activo</th>
          <th class="text-center">Acción</th>
        </tr>
      </thead>

      <tbody>
        @foreach ($socios as $socio)
          <tr>
            <td class="text-center">{{ $loop->index + 1 }}</td>
            <td class="text-center">{{ $socio->Nb_Socio }}</td>
            <td class="text-center">{{ $socio->Tx_Email }}</td>
            <td class="text-center">{{ $socio->Nu_Movil }}</td>
            <td class="text-center">{{ $socio->Nu_Calificacion }}</td>
            <td class="text-center">{{ $socio->St_Bloqueo }}</td>
            <td class="text-center">{{ $socio->St_Activo }}</td>

            <td>
              <form action="{{ route('socios.destroy', $socio->Co_Socio) }}" method="POST">
                <a class="btn btn-info" href="{{ route('socios.show', $socio->Co_Socio) }}">Ver</a>
                <a class="btn btn-primary" href="{{ route('socios.edit', $socio->Co_Socio) }}">Editar</a>
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Eliminar</button>
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
@endsection

resources/views/socios/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Socio</title>
</head>
<body>
  <h1>Socio</h1>
  <a href="{{ route('socios.index') }}">Regresar</a>

  <main>
    <p>
      <strong>ID: </strong>
      <span>{{ $socio->Co_Socio }}</span>
    </p>

    <p>
      <strong>Nombre: </strong>
      <span>{{ $socio->Nb_Socio }}</span>
    </p>

    <p>
      <strong>Identificación: </strong>
      <span>{{ $socio->Co_Identificacion }}</span>
    </p>

    <p>
      <strong>Email: </strong>
      <span>{{ $socio->Tx_Email }}</span>
    </p>

    <p>
      <strong>Movil: </strong>
      <span>{{ $socio->Nu_Movil }}</span>
    </p>

    <p>
      <strong>Calificación: </strong>
      <span>{{ $socio->Nu_Calificacion }}</span>
    </p>

    <p>
      <strong>Bloqueo: </strong>
      <span>{{ $socio->St_Bloqueo }}</span>
    </p>

    <p>
      <strong>Activo: </strong>
      <span>{{ $socio->St_Activo }}</span>
    </p>
  </main>
</body>
</html>

resources/views/usuario/create.blade.php
@section('content')

<div class="row">

    <div class="col-lg-12 margin-tb">

        <div class="pull-left">

            <h2>Add New Product</h2>

        </div>

        <div class="pull-right">

            <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>

        </div>

    </div>

</div>

   

@if ($errors->any())

    <div class="alert alert-danger">

        <strong>Whoops!</strong> There were some problems with your input.<br><br>

        <ul>

            @foreach ($errors->all() as $error)

                <li>{{ $error }}</li>

            @endforeach

        </ul>

    </div>

@endif

   

<form action="{{ route('products.store') }}" method="POST">

    @csrf

  

     <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name:</strong>

                <input type="text" name="name" class="form-control" placeholder="Name">

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Detail:</strong>

                <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail"></textarea>

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

        </div>

    </div>

   

</form>

@endsection

resources/views/usuario/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Amazon - Usuarios</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-success" href="{{ route('usuarios') }}">Crear registro</a>

            </div>

        </div>

    </div>



    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif



    <table class="table table-bordered">

            <thead>
            <tr class="text-center">
               <th class="text-center">No</th>
               <th class="text-center">Name</th>
               <th class="text-center">Email</th>
               <th class="text-center">Movil</th>
               <th class="text-center">Patron</th>
               <th class="text-center">Bloqueo</th>
               <th class="text-center">Activo</th>
               <th class="text-center">Action</th>
            </tr>
            </thead>

        @forelse ($usuarios as $usuario)

        <tr>
                <td class="text-center">{{ $loop->index + 1 }}</td>
                <td class="text-center">{{ $usuario->Nb_Usuario }}</td>
                <td class="text-center">{{ $usuario->Tx_Email }}</td>
                <td class="text-center">{{ $usuario->Nu_Movil }}</td>
                <td class="text-center">{{ $usuario->Tx_Patron }}</td>
                <td class="text-center">{{ $usuario->St_Bloqueo }}</td>
                <td class="text-center">{{ $usuario->St_Activo }}</td>

            <td>

                <form action="{{ route('usuarios',$usuario->Co_Usuario) }}" method="POST">



                    <a class="btn btn-info" href="{{ route('usuarios',$usuario->Co_Usuario) }}">Ver</a>



                    <a class="btn btn-primary" href="{{ route('usuarios',$usuario->Co_Usuario) }}">Editar</a>



                    @csrf

                    @method('DELETE')



                    <button type="submit" class="btn btn-danger">Eliminar</button>

                </form>

            </td>

        </tr>

        @endforeach

    </table>






@endsection
<!-- ------------------------------------ -->